### ISSUE TITLE
error windows 11

### ISSUE THREAD

**Issue by WhiteUnity** [new92/IGFI#57]
I am using a laptop on Windows 11 and I received this error when executing the program 
Traceback (most recent call last):
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://i.instagram.com/api/v1/friendships/create/787132/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\rafal\OneDrive\Documents\GitHub\IGFI\igfi.py", line 646, in <module>
    main(username=args.username.strip().lower(), password=args.password.strip(), session=args.session.replace('\\', '/'))
  File "c:\Users\rafal\OneDrive\Documents\GitHub\IGFI\igfi.py", line 400, in main
    client.user_follow(users[NAMES[j]])
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instagrapi\mixins\user.py", line 741, in user_follow
    result = self.private_request(f"friendships/create/{user_id}/", data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\rafal\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\instagrapi\mixins\private.py", line 323, in _send_private_request
    raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required

**Comment by new92** [comment]
@WhiteUnity you need to login to Instagram from your browser, follow the verification steps and run again IGFI.
