### ISSUE TITLE
Badpassword error

### ISSUE THREAD

**Issue by Doxtorian** [new92/IGFI#72]
Im getting the following error, I looked in other github that instagram is trying to block bots and some remedy is activating 2FA verification but even so, Im still getting this:

Status 429: Too many requests
Ignore 429: Continue login
Traceback (most recent call last):
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "igfi.py", line 655, in <module>
    main(username=args.username.strip().lower(), password=args.password.strip(), session=args.session.strip().replace('\\', '/'))
  File "igfi.py", line 355, in main
    login = client.login(username, password)
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\instagrapi\mixins\auth.py", line 391, in login
    logged = self.private_request("accounts/login/", data, login=True)
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\eduar\AppData\Roaming\Python\Python38\site-packages\instagrapi\mixins\private.py", line 344, in _send_private_request
    raise BadPassword(**last_json)
instagrapi.exceptions.BadPassword: The password you entered is incorrect. Please try again.

**Comment by new92** [comment]
Hey @Doxtorian try the following:
1. Check your password
2. If you have 2FA enabled try disabling it and run IGFI again
3. If the account you're using IGFI on is new it might take some days for it to work

**Comment by Doxtorian** [comment]
How many days aprox?

**Comment by new92** [comment]
15 maybe less
