### ISSUE TITLE
error : Some accounts prefer to manually review followers even when they're public. Let us know if you think we made a mistake.

### ISSUE THREAD

**Issue by dennyrizkismas** [new92/IGFI#73]
[+] Following Cristiano Ronaldo...
[✔] Ok
[+] Following Cardi B...
[✔] Ok
[+] Following Kim Kardashian...
[✔] Ok
[+] Following Ariana Grande...
[✔] Ok
[+] Following Nicki Minaj...
[✔] Ok
[+] Following Beyonce...
[✔] Ok
[+] Following Katy Perry...
[✔] Ok
[+] Following Selena Gomez...
[✔] Ok
[+] Following Justin Bieber...
[✔] Ok
[+] Following Lionel Messi...
[✔] Ok
[+] Following Neymar Jr...
[✔] Ok
[+] Following Kylian Mbappe...
[✔] Ok
[+] Following Dua Lipa...
[✔] Ok
Traceback (most recent call last):
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\instagrapi\mixins\private.py", line 298, in _send_private_request
    response.raise_for_status()
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/friendships/create/28527810/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Denny\IGFI\igfi.py", line 648, in <module>
    main(username=args.username.strip().lower(), password=args.password.strip(), session=args.session.strip().replace('\\', '/'))
  File "C:\Users\Denny\IGFI\igfi.py", line 618, in main
    main(username, password, session)
  File "C:\Users\Denny\IGFI\igfi.py", line 618, in main
    main(username, password, session)
  File "C:\Users\Denny\IGFI\igfi.py", line 401, in main
    client.user_follow(users[NAMES[j]])
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\instagrapi\mixins\user.py", line 741, in user_follow
    result = self.private_request(f"friendships/create/{user_id}/", data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\instagrapi\mixins\private.py", line 445, in private_request
    raise e
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\instagrapi\mixins\private.py", line 432, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\Denny\IGFI\igfi\Lib\site-packages\instagrapi\mixins\private.py", line 332, in _send_private_request
    raise FeedbackRequired(
instagrapi.exceptions.FeedbackRequired: feedback_required: Some accounts prefer to manually review followers even when they're public. Let us know if you think we made a mistake.

(igfi) C:\Users\Denny\IGFI>

**Comment by new92** [comment]
@dennyrizkismas you'll have to log in to the instagram account which you're attempting to increase its followers and follow the steps in the window which is poping up.
